name: Release Assets
on:
  release:
    types:
      - created
      - published

jobs:
  release:
    name: releaser
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang: [1.16.x]
    steps:
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        if: steps.semantic.outputs.new-release-published == 'true'
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      -
        name: Cache Go modules
        if: steps.semantic.outputs.new-release-published == 'true'
        uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key:          ${{ runner.os }}-go-${{ matrix.golang }}-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ matrix.golang }}-v1-
      -
        name: Bundle
        run:
          make bundle
      -
        name: Upload release asset
        if: steps.semantic.outputs.new-release-published == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{github.workspace}}/alfred-workflow-u.alfredworkflow
          asset_name: alfred-workflow-u.alfredworkflow
          asset_content_type: application/zip
